version = 1

[[annotations]]
path = "poetry.lock"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Software Freedom Conservancy <info@sfconservancy.org>"
SPDX-License-Identifier = "GPL-2.0-or-later"

[[annotations]]
path = "REUSE.toml"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Software Freedom Conservancy <info@sfconservancy.org>"
SPDX-License-Identifier = "GPL-2.0-or-later"

[[annotations]]
path = "tests/files/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Software Freedom Conservancy <info@sfconservancy.org>"
SPDX-License-Identifier = "GPL-2.0-or-later"
